FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential ocaml omake flex bison

COPY . /repo
WORKDIR /repo
RUN omake all
WORKDIR /repo/source

FROM ubuntu:20.04 as package
COPY --from=builder /repo/source/tjcc.opt /
RUN touch /test.sig
